Repository graycoreio/magento2-cors, pull requests merged in 2020-05, with the labels that each got.

#25 ci(all): run pr builds
  .azure/azure-pipelines.yml
Labels: bug

#26 ci(all): enable mysql service during integration test setup
  ci/scripts/integration-setup.sh
Labels: bug

#28 ci(all): pin covered Magento version to v2.3/php7.2-php7.3
  .azure/azure-pipelines.yml
  .azure/templates/integration-setup.yml
  ci/scripts/integration-setup.sh
Labels: bug, enhancement

#24 Prevent fatal error when using Chrome extensions for graphql querying
  Test/Unit/Validator/CorsValidatorTest.php
  Validator/CorsValidator.php
Labels: enhancement

#29 docs(all): setup basic docs and guidelines
  .github/CODEOWNERS
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/performance_issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  docs/DEVELOPER.md
Labels: documentation

#27 Add header provider for Access-Control-Allow-Credentials
  Configuration/CorsConfigurationInterface.php
  Configuration/GraphQl/CorsConfiguration.php
  Configuration/Rest/CorsConfiguration.php
  README.md
  Response/HeaderProvider/CorsAllowCredentialsHeaderProvider.php
  Response/HeaderProvider/CorsAllowOriginHeaderProvider.php
  Test/Unit/Configuration/GraphQlCorsConfigurationTest.php
  Test/Unit/Configuration/RestCorsConfigurationTest.php
  Test/Unit/HeaderProvider/CorsAllowCredentialsHeaderProviderTest.php
  Test/Unit/HeaderProvider/CorsAllowOriginHeaderProviderTest.php
  docs/stories/configuring-the-headers.md
  etc/config.xml
  etc/graphql/di.xml
  etc/webapi_rest/di.xml
Labels: documentation, enhancement
